# Generated by Django 3.1.3 on 2020-12-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_id', models.PositiveSmallIntegerField()),
                ('row_id', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.DurationField(help_text='tttt'),
        ),
    ]
